// This file was generated by scripts/parse-builds-equipment.ts, DO NOT EDIT MANUALLY
export interface Bg3BuildsEquipment {
  itemsByBuild: Record<string, string[]>;
  buildsByItem: Record<string, string[]>;
}
