// This file was generated by scripts/generate-item-data.ts, DO NOT EDIT MANUALLY

export interface Item {
  id: number;
  generalArea: string;
  type: string;
  name: string;
  effect: string[];
  source: string;
  location: string;
}
